//! Shared `MUSU_BRIDGE_TOKEN` resolver.
//!
//! Per V24-R3 wiki/493 Critic C4 (HIGH): the bridge bearer-token lookup was
//! duplicated in `auto_update.rs::read_ipc_token` and
//! `uninstall.rs::read_ipc_token`. R3's `control::bridge_client` would be the
//! third copy. This module extracts the single canonical resolver:
//!
//!   1. `MUSU_BRIDGE_TOKEN` env var (non-empty), THEN
//!   2. `<musu_home>/bridge.env` parsed line-by-line for `MUSU_BRIDGE_TOKEN=…`
//!
//! Both call sites preserve their previous behavior: skip blanks and `#`
//! comments, allow `export ` prefix, trim ASCII `"` / `'` from the value.
//! `auto_update.rs` and `uninstall.rs` now delegate to `read_bridge_token`;
//! `control::bridge_client` calls it directly.

use anyhow::{anyhow, Context, Result};
use std::path::Path;

/// Resolve the bridge bearer token. Returns `None` if neither source yields a
/// non-empty value. Callers decide whether absence is an error (control needs
/// it; uninstall/auto-update tolerate `None` and let musud reject).
pub fn read_bridge_token(home: &Path) -> Option<String> {
    if let Ok(t) = std::env::var("MUSU_BRIDGE_TOKEN") {
        if !t.is_empty() {
            return Some(t);
        }
    }
    let env_path = home.join("bridge.env");
    let body = std::fs::read_to_string(&env_path).ok()?;
    for line in body.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let line = line.strip_prefix("export ").unwrap_or(line);
        if let Some(rest) = line.strip_prefix("MUSU_BRIDGE_TOKEN=") {
            let val = rest.trim_matches(|c| c == '"' || c == '\'');
            if !val.is_empty() {
                return Some(val.to_string());
            }
        }
    }
    None
}

/// Read the account-wide mesh bearer (the shared cross-machine bridge bearer
/// issued by the cloud at mesh-join time, identical on every machine of one
/// account). Precedence: `MUSU_MESH_BEARER` env, then `<home>/mesh.env`. Returns
/// `None` when neither is set — the bridge then falls back to its per-machine
/// token (legacy behavior; cross-machine auth won't work until a join issues
/// the shared bearer). Mirrors read_bridge_token's parsing exactly.
pub fn read_mesh_bearer(home: &Path) -> Option<String> {
    if let Ok(t) = std::env::var("MUSU_MESH_BEARER") {
        let t = t.trim().to_string();
        if !t.is_empty() {
            return Some(t);
        }
    }
    let env_path = home.join("mesh.env");
    let body = std::fs::read_to_string(&env_path).ok()?;
    for line in body.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let line = line.strip_prefix("export ").unwrap_or(line);
        if let Some(rest) = line.strip_prefix("MUSU_MESH_BEARER=") {
            let val = rest.trim_matches(|c| c == '"' || c == '\'');
            if !val.is_empty() {
                return Some(val.to_string());
            }
        }
    }
    None
}

/// Persist the account-wide mesh bearer to `<home>/mesh.env` (0600 on unix).
/// Called by `musu mesh join-account` after the cloud returns it. Overwrites so
/// a re-join with a rotated secret replaces the old value. The bearer is a
/// shared account secret — same file discipline as bridge.env.
pub fn write_mesh_bearer(home: &Path, bearer: &str) -> Result<()> {
    let path = home.join("mesh.env");
    let tmp = home.join("mesh.env.tmp");
    let body = format!(
        "# musu mesh environment — generated by `musu mesh join-account`.\n\
         # Account-wide shared bridge bearer. Same on every machine of this\n\
         # account; that is intentional — it is how cross-machine tasks auth.\n\
         MUSU_MESH_BEARER={bearer}\n"
    );

    // Critic A2/A6 + Windows-ACL-first ordering:
    //
    // 1. Write to a SIBLING temp file, then atomically rename onto mesh.env.
    //    The rename closes the partial-read window — the runtime watcher (which
    //    re-reads mesh.env on change) never observes a half-written file.
    // 2. The ~/.musu directory itself is NOT ACL-hardened on Windows (only the
    //    files are). So on Windows we must restrict the temp file's ACL BEFORE
    //    the secret bytes land in it, otherwise the bearer is briefly
    //    world-readable on disk. We create the empty temp, lock its ACL, THEN
    //    write the secret, THEN rename.
    std::fs::create_dir_all(home).with_context(|| format!("create {}", home.display()))?;

    #[cfg(unix)]
    {
        use std::io::Write as _;
        use std::os::unix::fs::OpenOptionsExt as _;
        // Create the temp with 0600 from the start (mode applied at open so the
        // secret never lands in a world-readable file).
        let mut f = std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o600)
            .open(&tmp)
            .with_context(|| format!("create temp {}", tmp.display()))?;
        f.write_all(body.as_bytes())
            .with_context(|| format!("write temp {}", tmp.display()))?;
        f.sync_all().ok();
    }

    #[cfg(windows)]
    {
        // Create the empty temp first, lock its ACL, THEN write the secret.
        std::fs::write(&tmp, b"")
            .with_context(|| format!("create temp {}", tmp.display()))?;
        let user = windows_acl_principal()?;
        let output = std::process::Command::new("icacls")
            .arg(&tmp)
            .arg("/inheritance:r")
            .arg("/grant:r")
            .arg(format!("{user}:F"))
            .output()
            .context("spawn icacls")?;
        if !output.status.success() {
            let err = String::from_utf8_lossy(&output.stderr);
            let _ = std::fs::remove_file(&tmp);
            anyhow::bail!("icacls failed for mesh.env.tmp: {}", err.trim());
        }
        // ACL is now restricted; safe to write the secret bytes.
        std::fs::write(&tmp, body.as_bytes())
            .with_context(|| format!("write temp {}", tmp.display()))?;
    }

    // Atomic publish. On Windows std::fs::rename replaces the destination when
    // it exists on the same volume; on unix rename(2) is atomic.
    std::fs::rename(&tmp, &path).with_context(|| {
        // Best-effort cleanup of the temp on failure so we don't leave a
        // secret-bearing tmp around.
        let _ = std::fs::remove_file(&tmp);
        format!("atomic rename {} -> {}", tmp.display(), path.display())
    })?;
    Ok(())
}

/// Resolve the cloud **control-plane** token (distinct from the bridge bearer
/// token above). Per audit H3: this precedence was duplicated inline in
/// `room_work_orders.rs`, diverging from the bridge chain and making auth
/// failures path-dependent and hard to debug. Single canonical chain:
///
///   1. `MUSU_P2P_CONTROL_TOKEN` (non-empty), THEN
///   2. `MUSU_ROUTE_EVIDENCE_TOKEN`, THEN
///   3. `MUSU_TOKEN`, THEN
///   4. `crate::cloud::token::load_token(home)` (account token on disk)
///
/// Returns `None` when no source yields a non-empty value. This is the control
/// token used for owner-scoped room work-order claim/delivery; it is NOT the
/// bridge bearer token — keep the two resolvers separate on purpose.
pub fn read_control_token(home: &Path) -> Option<String> {
    for name in [
        "MUSU_P2P_CONTROL_TOKEN",
        "MUSU_ROUTE_EVIDENCE_TOKEN",
        "MUSU_TOKEN",
    ] {
        if let Ok(token) = std::env::var(name) {
            let token = token.trim().to_string();
            if !token.is_empty() {
                return Some(token);
            }
        }
    }
    crate::cloud::token::load_token(home)
        .map(|token| token.trim().to_string())
        .filter(|token| !token.is_empty())
}

/// Ensure a valid `bridge.env` exists under `home` and return the token.
///
/// Used by packaged startup paths where no prior `musu install` bootstrap may
/// have run yet, but the bridge still needs a production token to boot.
pub fn ensure_bridge_token(home: &Path) -> Result<String> {
    if let Some(token) = read_bridge_token(home) {
        return Ok(token);
    }

    let mut buf = [0u8; 32];
    getrandom::getrandom(&mut buf).map_err(|e| anyhow!("getrandom failed: {e}"))?;
    let token = hex::encode(buf);

    let path = home.join("bridge.env");
    let body = format!(
        "# musu bridge environment — generated automatically.\n\
         # Do NOT commit this file. Do NOT share the token.\n\
         MUSU_BRIDGE_TOKEN={token}\n"
    );
    std::fs::create_dir_all(home).with_context(|| format!("create {}", home.display()))?;
    std::fs::write(&path, body).with_context(|| format!("write {}", path.display()))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(&path)?.permissions();
        perms.set_mode(0o600);
        std::fs::set_permissions(&path, perms)
            .with_context(|| format!("chmod 600 {}", path.display()))?;
    }

    #[cfg(windows)]
    {
        let user = windows_acl_principal()?;
        let output = std::process::Command::new("icacls")
            .arg(&path)
            .arg("/inheritance:r")
            .arg("/grant:r")
            .arg(format!("{user}:F"))
            .output()
            .context("spawn icacls")?;
        if !output.status.success() {
            let err = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("icacls failed: {}", err.trim());
        }
    }

    Ok(token)
}

#[cfg(windows)]
fn windows_acl_principal() -> Result<String> {
    let user = std::env::var("USERNAME").context("USERNAME env var")?;
    let domain = std::env::var("USERDOMAIN").unwrap_or_default();
    if domain.is_empty() || user.contains('\\') || domain.eq_ignore_ascii_case(&user) {
        Ok(user)
    } else {
        Ok(format!("{domain}\\{user}"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    /// Process-global lock — `cargo test` runs `#[test]` fns concurrently by
    /// default and `std::env::set_var` / `remove_var` race across tests in
    /// the same binary. Serializing the three env-touching tests here keeps
    /// us safe without pulling in `serial_test` as a new dev-dep.
    static ENV_LOCK: Mutex<()> = Mutex::new(());

    /// `MUSU_BRIDGE_TOKEN` env wins over the file.
    #[test]
    fn env_var_takes_precedence() {
        let _guard = ENV_LOCK.lock().expect("env lock");
        std::env::set_var("MUSU_BRIDGE_TOKEN", "env-wins");
        let home = std::env::temp_dir().join("musu-rs-token-test-env");
        std::fs::create_dir_all(&home).ok();
        std::fs::write(home.join("bridge.env"), "MUSU_BRIDGE_TOKEN=file-loses\n").ok();
        let result = read_bridge_token(&home);
        // Reset BEFORE the assertion so even a panic doesn't leak state to
        // the next test (Mutex drop happens regardless via Drop).
        std::env::remove_var("MUSU_BRIDGE_TOKEN");
        assert_eq!(result, Some("env-wins".into()));
    }

    #[test]
    fn empty_env_falls_back_to_file() {
        let _guard = ENV_LOCK.lock().expect("env lock");
        std::env::remove_var("MUSU_BRIDGE_TOKEN");
        let home = std::env::temp_dir().join("musu-rs-token-test-file");
        std::fs::create_dir_all(&home).ok();
        std::fs::write(
            home.join("bridge.env"),
            "# comment\nexport MUSU_BRIDGE_TOKEN=\"quoted-val\"\n",
        )
        .ok();
        assert_eq!(read_bridge_token(&home), Some("quoted-val".into()));
    }

    #[test]
    fn missing_everything_returns_none() {
        let _guard = ENV_LOCK.lock().expect("env lock");
        std::env::remove_var("MUSU_BRIDGE_TOKEN");
        let home = std::env::temp_dir().join("musu-rs-token-test-missing");
        std::fs::create_dir_all(&home).ok();
        let _ = std::fs::remove_file(home.join("bridge.env"));
        assert_eq!(read_bridge_token(&home), None);
    }

    #[test]
    fn ensure_bridge_token_creates_bridge_env() {
        let _guard = ENV_LOCK.lock().expect("env lock");
        std::env::remove_var("MUSU_BRIDGE_TOKEN");
        let home = std::env::temp_dir().join("musu-rs-token-test-ensure");
        let _ = std::fs::remove_dir_all(&home);
        std::fs::create_dir_all(&home).ok();
        let _ = std::fs::remove_file(home.join("bridge.env"));

        let token = ensure_bridge_token(&home).expect("ensure token");
        assert_eq!(token.len(), 64);
        assert_eq!(read_bridge_token(&home), Some(token));
    }

    #[test]
    fn write_then_read_mesh_bearer_roundtrips() {
        let _guard = ENV_LOCK.lock().expect("env lock");
        std::env::remove_var("MUSU_MESH_BEARER");
        let home = std::env::temp_dir().join("musu-rs-token-test-mesh-rt");
        let _ = std::fs::remove_dir_all(&home);
        std::fs::create_dir_all(&home).ok();

        assert_eq!(read_mesh_bearer(&home), None, "absent before write");
        write_mesh_bearer(&home, "deadbeef0123").expect("write mesh bearer");
        assert_eq!(read_mesh_bearer(&home), Some("deadbeef0123".to_string()));

        // Re-join with a rotated bearer overwrites.
        write_mesh_bearer(&home, "cafef00d4567").expect("rewrite");
        assert_eq!(read_mesh_bearer(&home), Some("cafef00d4567".to_string()));
        let _ = std::fs::remove_dir_all(&home);
    }

    /// After the atomic ACL-first rewrite, a deleted/emptied mesh.env yields
    /// `None` from `read_mesh_bearer`, and feeding that `None` into the auth
    /// cell's `swap_peer_token` must PRESERVE the prior bearer (the empty-swap
    /// guard, Critic A3). This is the file-level half of that guarantee; the
    /// cell-level half lives in `bridge::auth` tests.
    #[test]
    fn deleted_mesh_env_reads_none_after_atomic_write() {
        let _guard = ENV_LOCK.lock().expect("env lock");
        std::env::remove_var("MUSU_MESH_BEARER");
        let home = std::env::temp_dir().join("musu-rs-token-test-mesh-del");
        let _ = std::fs::remove_dir_all(&home);
        std::fs::create_dir_all(&home).ok();

        write_mesh_bearer(&home, "deadbeef0123").expect("write");
        assert_eq!(read_mesh_bearer(&home), Some("deadbeef0123".to_string()));
        // No leftover temp after the atomic publish.
        assert!(
            !home.join("mesh.env.tmp").exists(),
            "mesh.env.tmp must be consumed by the atomic rename"
        );

        // Delete the file → read yields None (caller's swap must then no-op).
        std::fs::remove_file(home.join("mesh.env")).expect("delete");
        assert_eq!(
            read_mesh_bearer(&home),
            None,
            "deleted mesh.env must read None"
        );
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn mesh_bearer_env_overrides_file() {
        let _guard = ENV_LOCK.lock().expect("env lock");
        let home = std::env::temp_dir().join("musu-rs-token-test-mesh-env");
        let _ = std::fs::remove_dir_all(&home);
        std::fs::create_dir_all(&home).ok();
        write_mesh_bearer(&home, "from-file").expect("write");

        std::env::set_var("MUSU_MESH_BEARER", "from-env");
        assert_eq!(read_mesh_bearer(&home), Some("from-env".to_string()));
        std::env::remove_var("MUSU_MESH_BEARER");
        assert_eq!(read_mesh_bearer(&home), Some("from-file".to_string()));
        let _ = std::fs::remove_dir_all(&home);
    }

    /// Control-token chain (audit H3). Serialized under the same ENV_LOCK
    /// because it touches the shared control-token env vars.
    fn clear_control_env() {
        std::env::remove_var("MUSU_P2P_CONTROL_TOKEN");
        std::env::remove_var("MUSU_ROUTE_EVIDENCE_TOKEN");
        std::env::remove_var("MUSU_TOKEN");
    }

    /// `MUSU_P2P_CONTROL_TOKEN` wins over the other control sources.
    #[test]
    fn control_token_prefers_p2p_control() {
        let _guard = ENV_LOCK.lock().expect("env lock");
        clear_control_env();
        std::env::set_var("MUSU_P2P_CONTROL_TOKEN", "p2p-wins");
        std::env::set_var("MUSU_ROUTE_EVIDENCE_TOKEN", "route-loses");
        std::env::set_var("MUSU_TOKEN", "generic-loses");
        let home = std::env::temp_dir().join("musu-rs-control-test-p2p");
        std::fs::create_dir_all(&home).ok();
        let result = read_control_token(&home);
        clear_control_env();
        assert_eq!(result, Some("p2p-wins".into()));
    }

    /// Falls through P2P -> ROUTE_EVIDENCE -> MUSU_TOKEN in order.
    #[test]
    fn control_token_falls_through_to_route_then_generic() {
        let _guard = ENV_LOCK.lock().expect("env lock");
        clear_control_env();
        std::env::set_var("MUSU_ROUTE_EVIDENCE_TOKEN", "route-wins");
        std::env::set_var("MUSU_TOKEN", "generic-loses");
        let home = std::env::temp_dir().join("musu-rs-control-test-route");
        std::fs::create_dir_all(&home).ok();
        let route = read_control_token(&home);
        std::env::remove_var("MUSU_ROUTE_EVIDENCE_TOKEN");
        let generic = read_control_token(&home);
        clear_control_env();
        assert_eq!(route, Some("route-wins".into()));
        assert_eq!(generic, Some("generic-loses".into()));
    }

    /// Blank env values are skipped, not returned as empty tokens.
    #[test]
    fn control_token_skips_blank_env() {
        let _guard = ENV_LOCK.lock().expect("env lock");
        clear_control_env();
        std::env::set_var("MUSU_P2P_CONTROL_TOKEN", "   ");
        std::env::set_var("MUSU_ROUTE_EVIDENCE_TOKEN", "real");
        let home = std::env::temp_dir().join("musu-rs-control-test-blank");
        std::fs::create_dir_all(&home).ok();
        let result = read_control_token(&home);
        clear_control_env();
        assert_eq!(result, Some("real".into()));
    }
}
