version: "3.8"
services:
  neko:
    image: "m1k1o/neko:xfce"
    restart: unless-stopped
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: musu
      NEKO_PASSWORD_ADMIN: musuadmin
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
    cap_add:
      - SYS_ADMIN
