export function handleGetNetworkRunbook() {
  return {
    product_name: "MUSU Private Mesh",
    default_mode: "musu_headscale",
    forbidden_default: "Do not require or suggest Tailscale.com signup to use MUSU.",
    modes: [
      {
        id: "local_lan",
        label: "Local/LAN",
        use_when: "Machines can directly reach each other on the same host or LAN.",
        account_requirement: "none",
        operator_rule: "Probe MUSU bridge/node discovery and direct bridge /health before any overlay setup.",
      },
      {
        id: "musu_headscale",
        label: "MUSU-managed or operator-managed Headscale",
        use_when: "Machines are on different networks and need a private overlay without Tailscale.com.",
        account_requirement: "no Tailscale.com account",
        operator_rule: "Create a MUSU Headscale + Caddy HTTPS + embedded DERP bundle with `musu mesh bootstrap`, then create a `musu.device_add.v1` pass for each node before joining.",
      },
      {
        id: "external_tailscale_opt_in",
        label: "External Tailscale.com tailnet",
        use_when: "The user explicitly chooses their existing external managed tailnet.",
        account_requirement: "external Tailscale.com account chosen by user",
        operator_rule: "Never present this as required MUSU setup.",
      },
    ],
    headscale_runbook: [
      "Start with same-machine and LAN reachability.",
      "Run musu mesh status --json to classify this machine before claiming a mesh route.",
      "Require mode=musu_headscale, control_server_url, and control_server_verified=true before treating a callback proof as MUSU Private Mesh proof.",
      "Provision a no-signup Headscale + Caddy HTTPS + MUSU-owned embedded DERP bundle with `musu mesh bootstrap --server-url https://<mesh-host> --output <bundle-dir>`.",
      "Point DNS for <mesh-host> at the control host before enrolling machines; the default generated bundle includes Caddy as the public HTTPS reverse proxy.",
      "Deploy the generated bundle on a stable host that is reachable before the tailnet exists.",
      "Expose tcp/80 and tcp/443 for Caddy HTTPS plus udp/3478 for embedded DERP/STUN; pass --derp-ipv4 and/or --derp-ipv6 for stronger DERP-map stability.",
      "Run `docker compose config --quiet`, `docker compose up -d`, and `docker compose exec headscale headscale health` in the generated bundle before creating join keys.",
      "Run the generated public endpoint check (`scripts/check-public-endpoint.ps1` or `.sh`) and require DNS, tcp/443, and `https://<mesh-host>/health` to pass before sharing a device-add pass.",
      "Create a one-use device-add pass with the generated bundle helper: scripts/create-join-key.ps1 or scripts/create-join-key.sh. The helper writes a file under `device-add-passes/`; every valid pass requires one_time_key=true, reusable=false, `created_at_utc`, and `expires_after_seconds=3600`. Join rejects passes whose `created_at_utc` is more than 300 seconds in the future, so clock skew cannot extend the one-hour window. The helper prints only the file path plus the target-side `musu mesh join --device-add-pass <musu.device_add.v1.json>` command. It must not print the raw pass JSON or a raw authkey join command as the default UX.",
      "Copy the generated MUSU device-add pass file to the target PC instead of exposing raw Headscale preauth-key command shape to the user.",
      "On the target PC, save the pass to a local `musu.device_add.v1.json` file and run `musu mesh join --device-add-pass <musu.device_add.v1.json>`; do not paste the secret-bearing JSON inline into a shell command. The command consumes the embedded login server/authkey, rechecks `<headscale-url>/health` before it can set control_server_verified=true, and after a successful non-dry-run join writes a redacted `.used-<timestamp>` marker (`musu.device_add.consumed.v1`) and deletes the original secret-bearing pass file. If the report includes `device_add_pass_cleanup_error`, delete the original pass manually before continuing.",
      "Join each MUSU machine with `musu mesh join`; do not tell the user to sign up for Tailscale.com, and do not treat --dry-run or --skip-control-health as verified setup.",
      "Capture every node address with tailscale ip -4.",
      "Run musu mesh doctor --json if status reports external_tailscale_opt_in or missing control_server_url.",
      "Run musu mesh verify --target-ip <target-tailnet-ip> before claiming peer bridge reachability.",
      "Verify overlay reachability with tailscale ping --timeout=5s --c=1 <target-tailnet-ip>.",
      "Verify embedded DERP when needed with tailscale debug derp headscale.",
      "Verify MUSU bridge reachability at http://<target-tailnet-ip>:<bridge-port>/health.",
      "Generate physical peer evidence on the target PC with `musu mesh physical-peer-evidence --json`, copy both the JSON and its `.sha256` sidecar to the same folder on the source PC, then run release proof with the JSON path. The evidence must include a target hostname, and release peer identity must show source_hostname, target_hostname, and physical_host_distinct=true.",
      "For release proof, prefer `scripts/windows/run-private-mesh-release-proof.ps1 -PhysicalPeerEvidencePath <copied-target-pc-physical-peer-evidence.json>` so status, verify, delegated route proof, callback proof, evidence hashing, native release proof, physical-peer verification, verifier judgment, final bundle manifest, and final archive zip are captured together.",
      "The release-proof runner automatically writes `private-mesh-release-proof.bundle-manifest.json`; require schema=musu.private_mesh_release_proof_bundle.v1, ok=true, fail_count=0, and listed SHA256 sidecars before using the proof in a release claim.",
      "The same runner also creates a release archive via `scripts/windows/archive-private-mesh-release-proof-bundle.ps1`; require `private-mesh-release-proof.archive.json` with schema=musu.private_mesh_release_proof_archive.v1, ok=true, release_evidence_trusted=true, bundle_manifest_ok=true, bundle_manifest_fail_count=0, archive_zip_path present, and matching archive manifest `.sha256` before final success.",
      "When rechecking a saved proof folder, run `scripts/windows/verify-private-mesh-release-proof-bundle.ps1 -EvidenceRoot <proof-folder> -Json` and require the same bundle manifest result.",
      "When preserving a saved proof folder, run `scripts/windows/archive-private-mesh-release-proof-bundle.ps1 -EvidenceRoot <proof-folder> -Json` and archive the resulting zip plus archive manifest sidecar.",
      "When rechecking saved proof, run scripts/windows/verify-private-mesh-route-proof-evidence.ps1 against private-mesh-route-proof.evidence.json; require the JSON verifier to return ok=true before using the proof in a release claim.",
      "Run a delegated task and require callback reconciliation into the source cockpit.",
      "Do not mark release_grade=true unless control-server verification, tailnet ping, bridge health, delegated route proof, callback reconciliation, and target_callback_match=true are all true.",
    ],
    verification_required: [
      "source tailscale ip -4 output",
      "target 100.64.0.0/10 tailnet IPv4 address",
      "mode=musu_headscale with control_server_url and control_server_verified=true",
      "tailscale ping success from source to target",
      "target MUSU bridge /health success over the tailnet IP",
      "delegated task route proof",
      "callback_delivered=true at the source cockpit",
      "verified_target_tailnet_ip equals callback_tailnet_ip equals the expected target IP",
      "target_callback_match=true in both status and verification objects",
      "physical peer evidence generated on the target physical PC with target hostname present",
      "native peer_identity includes source_hostname, target_hostname, and physical_host_distinct=true",
      "release_evidence_trusted=true in native or runner release proof output",
      "private mesh release proof bundle manifest with ok=true and fail_count=0",
      "private mesh release proof archive manifest with ok=true, bundle_manifest_ok=true, bundle_manifest_fail_count=0, and archive_zip_path present",
    ],
    constraints: [
      "Headscale is BSD-3-Clause licensed; source/binary redistributions must preserve license notices and disclaimers.",
      "Do not use Headscale copyright holder or contributor names to endorse MUSU without permission.",
      "Do not brand MUSU as a Tailscale product; Tailscale and WireGuard are registered trademarks of their owners.",
      "musu mesh join must use tailscale up --login-server, never plain tailscale login as the default path.",
      "musu mesh join must not mark control_server_verified=true unless the public Headscale /health endpoint was checked successfully during the real join.",
      "Headscale's stated scope is a narrow, single-tailnet control server for personal/lab/small-organization use.",
      "For many customers, isolate owners by separate tailnet/control-plane instance or prove multi-tenant isolation before launch.",
      "Headscale does not currently replace every Tailscale SaaS feature, including Funnel, Serve, and network flow logs.",
      "MUSU bootstrap defaults to Headscale embedded DERP and removes the upstream Tailscale DERP map; this removes the default Tailscale relay dependency but still needs redundant MUSU/operator DERP before high-availability claims.",
      "Running Headscale on a machine that is itself inside the tailnet is not a supported deployment shape.",
    ],
    official_docs_snapshot: {
      date: "2026-06-13",
      headscale_repo_path: "docs/vendor/official-network-docs/headscale",
      headscale_commit: "21058d11424d5121dbc1eeb3ba0a39d2f462bfcc",
      tailscale_docs_manifest: "docs/vendor/official-network-docs/tailscale-docs/manifest.json",
      tailscale_docs_downloaded: 575,
      tailscale_docs_failed: 0,
    },
    source_urls: [
      "https://github.com/juanfont/headscale",
      "https://github.com/juanfont/headscale/blob/main/LICENSE",
      "https://headscale.net/stable/about/features/",
      "https://headscale.net/stable/about/faq/",
      "https://headscale.net/stable/ref/derp/",
      "https://headscale.net/stable/usage/getting-started/",
      "https://tailscale.com/docs/how-to/set-up-custom-control-server",
      "https://tailscale.com/docs/reference/tailscale-cli",
      "https://tailscale.com/opensource",
    ],
  };
}
